[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "regulens-ai"
version = "1.1.0"
requires-python = ">=3.12"

[project.optional-dependencies]
development = [
    "pytest>=7.0",
]
