[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "regulens-ai"
version = "0.0.1"
requires-python = ">=3.11"

[project.optional-dependencies]
development = [
    "pytest>=7.0",
]
